//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRERH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE
    {
        public int ID_DETALLE { get; set; }
        public string EXPERIENCIA { get; set; }
        public string GRADO_ACADEMICO { get; set; }
        public Nullable<int> ID_TECNOLOGIA { get; set; }
    
        public virtual TECNOLOGIA TECNOLOGIA { get; set; }
    }
}
